# TailExplorer 配置文件示例
# 复制此文件为 config.yaml 并根据您的环境进行配置

log_sources:
  # Docker Compose 日志源示例
  webapp:
    name: "Web应用日志"
    type: "docker-compose"
    command: "docker-compose logs -f --tail=100"
    working_dir: "/path/to/your/compose/project"
    description: "Web应用的 Docker Compose 日志"
    
  api-server:
    name: "API服务日志"
    type: "docker-compose"
    command: "docker-compose logs api --tail=500 -f"
    working_dir: "/path/to/your/api/project"
    description: "API服务容器日志"
    
  # 文件日志源示例
  nginx-access:
    name: "Nginx 访问日志"
    type: "file"
    command: "tail -f -n 100 /var/log/nginx/access.log"
    working_dir: "/"
    description: "Nginx 访问日志文件"
    
  nginx-error:
    name: "Nginx 错误日志"
    type: "file"
    command: "tail -f -n 100 /var/log/nginx/error.log"
    working_dir: "/"
    description: "Nginx 错误日志文件"
    
  app-logs:
    name: "应用日志文件"
    type: "file"
    command: "tail -f -n 200 /var/log/myapp/app.log"
    working_dir: "/"
    description: "应用程序日志文件"
    
  # 系统日志源示例
  syslog:
    name: "系统日志"
    type: "system"
    command: "journalctl -f -n 100"
    working_dir: "/"
    description: "系统 journalctl 日志"
    
  docker-daemon:
    name: "Docker守护进程日志"
    type: "system"
    command: "journalctl -u docker -f -n 50"
    working_dir: "/"
    description: "Docker守护进程的系统日志"

# 服务器配置
server:
  host: "0.0.0.0"
  port: 8000
  reload: true
  log_level: "info"

# 安全配置
security:
  # 访问密码（必须设置）
  password: "your_secure_password_here"
  # 会话过期时间（小时）
  session_expire_hours: 24

# 日志配置
logging:
  max_lines_per_source: 10000  # 每个日志源最大保存行数
  cleanup_threshold: 5000      # 清理阈值，超过时保留的行数
